version: "{build}"
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
build_script:
  - ps: .\build.ps1
test: on
artifacts:
  - path: \src\BuildArtifacts\*.nupkg
    name: NuGet
skip_commits:
  message: /^\[nobuild\](.*)?/ # Skip build if commit message starts with [nobuild]
deploy:
- provider: GitHub
  tag: c#
  release: Crate
  description: Framework for Vertical Slice architecture
  auth_token:
    secure: whXHuF90Fu558DpfESkMf/QtMCuJxkX8JXryU+ted+TGl0MCJw4vs+vJC+dK4jrI
  repository: vonbv25/Von.Crate
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: master
- provider: NuGet
    server: https://nuget.pkg.github.com/vonbv25/index.json
    api_key:
      secure: whXHuF90Fu558DpfESkMf/QtMCuJxkX8JXryU+ted+TGl0MCJw4vs+vJC+dK4jrI  # You can encrypt your API key using AppVeyor's encryption
    on:
      branch: master  # Deploy on the master branch or any other branch as needed
