version: "{build}"
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
nuget:
  disable_publish_on_pr: true
build_script:
  - ps: .\build.ps1
test: on
artifacts:
  - path: .\BuildArtifacts\*.nupkg
    name: NuGet
skip_commits:
  message: /^\[nobuild\](.*)?/ # Skip build if commit message starts with [nobuild]
