version: "{build}"
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
build_script:
  - ps: .\build.ps1
test: on
artifacts:
  - path: .src\BuildArtifacts\*.nupkg
    name: NuGet
skip_commits:
  message: /^\[nobuild\](.*)?/ # Skip build if commit message starts with [nobuild]
deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: DdCc4QnTvtI6GR7/nTsilzxdjScMYHDlMi6GHk/Ycnw=
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*(\.|\.s)nupkg/